engine: knitr

project:
  type: website
  render:
    - "*.qmd"
    - "!downloads/**"
  resources:
    - downloads/
    - figures/

website:
  title: "ISPE 2026 Simulation Workshop"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Introduction"
        href: index.qmd
      - text: "Designing a Simulation Study"
        href: overview.qmd
      - section: Activities
        contents:
          - activity-1.qmd
          - activity-2.qmd
          - activity-3.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
